name: cms-express

services:
  server:
    image: node:lts-slim
    working_dir: /usr/share/app
    volumes:
      - .:/usr/share/app
    ports:
      - 3000:3000
    tty: true
    entrypoint:
      - npm
      - run
      - dev
